

export const EMAIL_VARIFICATION ="EMAIL_VARIFICATION"
export const AUTH_LOGIN = "AUTH_LOGIN"

export const LOGIN_FORM = "LOGIN_FORM"
export const LOGED_FORM = "LOGED_FORM"

export const LOGOUT_USER = "LOGOUT_USER"
export const LOGGEDOUT_USER = "LOGGEDOUT_USER"

export const GOOGLE_LOGIN = "GOOGLE_LOGIN"

export const FORGOT_PASSWORD = "FORGOT_PASSWORD"


export const SET_ALERT = "SET_ALERT"
export const RESET_ALERT = "RESET_ALERT"

export const GET_PRODUCT = "GET_PRODUCT"
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT"
export const POST_PRODUCT= "POST_PRODUCT"
export const LOADING_PRODUCT = "LOADING_PRODUCT"
export const ERROE_PRODUCT = "ERROE_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"


export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const CLEAR_CART = "CLEAR_CART"



export const GET_COUSTOMER = "GET_COUSTOMER"
export const POST_COUSTOMER = "POST_COUSTOMER"
export const LOADING_COUSTOMER = "LOADING_COUSTOMER"
export const ERROE_COUSTOMER = "ERROE_COUSTOMER"


export const GET_CATEGORY = "GET_CATEGORY"
export const POST_CATEGORY= "POST_CATEGORY"
export const DELETE_CATEGORY = "DELETE_CATEGORY"
export const UPDATE_CATEGORY = "UPDATE_CATEGORY"
export const LOADING_CATEGORY = "LOADING_CATEGORY"
export const ERROE_CATEGORY = "ERROE_CATEGORY"
