

export const EMAIL_VARIFICATION ="EMAIL_VARIFICATION"
export const AUTH_LOGIN = "AUTH_LOGIN"

export const LOGIN_FORM = "LOGIN_FORM"
export const LOGED_FORM = "LOGED_FORM"

export const LOGOUT_USER = "LOGOUT_USER"
export const LOGGEDOUT_USER = "LOGGEDOUT_USER"

export const GOOGLE_LOGIN = "GOOGLE_LOGIN"

export const FORGOT_PASSWORD = "FORGOT_PASSWORD"


export const SET_ALERT = "SET_ALERT"
export const RESET_ALERT = "RESET_ALERT"

export const GET_PRODUCT = "GET_PRODUCT"
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT"
export const POST_PRODUCT= "POST_PRODUCT"
export const LOADING_PRODUCT = "LOADING_PRODUCT"
export const ERROE_PRODUCT = "ERROE_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"

